#The playbook is to launch a instance in aws
#usage: ansible-playbook instance-launch.yml -e name=namegoeshere -v
#Author: sathishm
#
---
- name: Provision EC2 Instance
  hosts: local
  connection: local
  gather_facts: no
  vars_files: 
    - vars/all.yml

  tasks:
    - name: Launching EC2 Instance
      ec2:
        aws_access_key: "{{aws_access_key}}"
        aws_secret_key: "{{aws_secret_key}}"
        vpc_subnet_id: "{{vpc_subnet_id}}"
        group_id: "{{security_group}}"
        instance_type: "{{instance_type}}"
        image: "{{image}}"
        wait: true 
        region: "{{region}}"
        keypair: "{{keypair}}"
        count: "{{count}}"
        volumes:
          - device_name: /dev/sda1
            volume_type: gp2
            volume_size: 50
        instance_tags:
            Name: "{{name}}"
      register: ec2

    - name: Wait for SSH to come up
      wait_for: 
        host: "{{item.private_ip}}"
        port: 22
        state: started
      with_items: "{{ ec2.instances }}"

    - name: Add instance to local host group
      become: yes
      local_action: lineinfile 
                    dest="hosts" 
                    regexp="{{item.private_ip}}"
                    insertafter="[rhel]" 
                    line="{{item.private_ip}} hostname={{name}}" 
                    state="present"
      with_items: "{{ec2.instances}}"

    - name: Register public key
      become: yes
      shell: cat ~/.ssh/id_rsa.pub | ssh -i ~/.ssh/abc.pem -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ec2-user@{{item.private_ip}} 'cat >> ~/.ssh/authorized_keys'
      with_items: "{{ ec2.instances }}"
