---

- name: Install curl
  apt: name={{item}} state=present
  with_items:
  - curl
  - python-pycurl

- name: Add the RabbitMQ APT key
  apt_key: url=http://www.rabbitmq.com/rabbitmq-signing-key-public.asc state=present

- name: Add the RabbitMQ source to the APT source list
  apt_repository: repo="deb http://www.rabbitmq.com/debian/ testing main" state=present

- name: Install RabbitMQ
  apt: name={{ item }} state=present
  with_items:
  - erlang-nox
  - rabbitmq-server

- name: Create SSL directory for RabbitMQ
  file: path=/etc/rabbitmq/ssl state=directory

- name: Copy cert.pem to /etc/rabbitmq/ssl
  template: src=cert.pem dest=/etc/rabbitmq/ssl/cert.pem

- name: Copy cacert.pem to /etc/rabbitmq/ssl
  template: src=cacert.pem dest=/etc/rabbitmq/ssl/cacert.pem

- name: Copy key.pem to /etc/rabbitmq/ssl
  template: src=key.pem dest=/etc/rabbitmq/ssl/key.pem

- name: Config rabbitmq
  template: src=rabbitmq.config dest=/etc/rabbitmq/rabbitmq.config

- name: Restart RabbitMQ services
  service: name={{ item }} state=restarted
  with_items:
  - rabbitmq-server

- name: Create a RabbitMQ virtual host
  shell: rabbitmqctl add_vhost /sensu
  ignore_errors: True
  register: error1

- debug: var=error1

- name: Create a user for Sensu
  shell: rabbitmqctl add_user {{ rabbitmq_user }} {{ rabbitmq_password }}
  ignore_errors: True
  register: error2

- debug: var=error2

- name: Set permissions Sensu user
  shell: rabbitmqctl set_permissions -p /sensu {{ rabbitmq_user }} ".*" ".*" ".*"
  changed_when: False

- name: Install redis-server
  apt: name={{ item }} state=present
  with_items:
  - redis-server
  
- name: Config redis
  template: src=redis.conf dest=/etc/redis/redis.conf

- name: Restart Redis services
  service: name={{ item }} state=restarted
  with_items:
  - redis-server

- name: Add the sensu APT key
  apt_key: url=http://repos.sensuapp.org/apt/pubkey.gpg state=present

- name: Add the sensu source to the APT source list
  apt_repository: repo="deb http://repos.sensuapp.org/apt sensu main" state=present

- name: Install sensu&uchiwa
  apt: name={{ item }} state=present
  with_items:
  - sensu 
  - uchiwa
  - ruby
  - ruby-dev
  - build-essential
  - postfix
  - mailutils
  
- name: Install sensu gem
  gem: name={{ item }} state=present
  with_items:
  - sensu-plugin

- name: Create SSL directory for sensu&uchiwa
  file: path=/etc/sensu/ssl state=directory

- name: Copy cert.pem to /etc/sensu/ssl
  template: src=cert.pem dest=/etc/sensu/ssl/cert.pem

- name: Copy key.pem to /etc/sensu/ssl
  template: src=key.pem dest=/etc/sensu/ssl/key.pem

- name: Copy rabbitmq.j2 to /etc/sensu/conf.d
  template: src=rabbitmq.j2 dest=/etc/sensu/conf.d/rabbitmq.json

- name: Copy redis.j2 to /etc/sensu/conf.d
  template: src=redis.j2 dest=/etc/sensu/conf.d/redis.json

- name: Copy api.j2 to /etc/sensu/conf.d
  template: src=api.j2 dest=/etc/sensu/conf.d/api.json

- name: Copy uchiwa.j2 to /etc/sensu/conf.d
  template: src=uchiwa.j2 dest=/etc/sensu/conf.d/uchiwa.json

- name: Copy client.j2 to /etc/sensu/conf.d
  template: src=client.j2 dest=/etc/sensu/conf.d/client.json

- name: Update sensu-server,client,api,uchiwa services
  shell: update-rc.d {{item}} defaults
  with_items:
  - sensu-server
  - sensu-client
  - sensu-api
  - uchiwa

- name: Restart sensu-server,client,api,uchiwa services
  service: name={{ item }} state=restarted
  with_items:
  - sensu-server
  - sensu-client
  - sensu-api
  - uchiwa

