---
- name: Install curl
  apt: name={{item}} state=present
  with_items:
  - curl
  - python-pycurl

- name: Add the Sensu APT key
  apt_key: url=http://repos.sensuapp.org/apt/pubkey.gpg state=present

- name: Add the Sensu source to the APT source list
  apt_repository: repo="deb http://repos.sensuapp.org/apt sensu main" state=present

- name: Install sensu
  apt: name={{ item }} state=present
  with_items:
  - sensu
  - ruby
  - ruby-dev
  - build-essential
  - postfix
  - mailutils
  
- name: Install sensu gem
  gem: name={{ item }} state=present
  with_items:
  - mixlib-cli
  - sensu-plugin

- name: Create SSL directory for sensu
  file: path=/etc/sensu/ssl state=directory

- name: Copy cert.pem to /etc/sensu/ssl
  template: src=cert.pem dest=/etc/sensu/ssl/cert.pem

- name: Copy key.pem to /etc/sensu/ssl
  template: src=key.pem dest=/etc/sensu/ssl/key.pem

- name: Copy rabbitmq.j2 to /etc/sensu/conf.d
  template: src=rabbitmq.j2 dest=/etc/sensu/conf.d/rabbitmq.json

- name: Copy client.j2 to /etc/sensu/conf.d
  template: src=client.j2 dest=/etc/sensu/conf.d/client.json

- name: Copy api.j2 to /etc/sensu/conf.d
  template: src=api.j2 dest=/etc/sensu/conf.d/api.json

- name: Copy redis.j2 to /etc/sensu/conf.d
  template: src=redis.j2 dest=/etc/sensu/conf.d/redis.json

- name: Update sensu-server,client,api services
  shell: update-rc.d {{item}} defaults
  with_items:
  - sensu-client
  - sensu-server
  - sensu-api
      
- name: Restart sensu-server,client,api services
  service: name={{ item }} state=restarted
  with_items:
  - sensu-client
  - sensu-server
  - sensu-api

